## 1. numpy, scipy 이용해 다양한 선형대수 연산하기

### 기본 라이브러리 불러오기

In [1]:
import numpy as np
from scipy import linalg, sparse

### 다양한 행렬 생성하고 출력하기
- A, B, C는 랜덤하게 생성된 행렬이기 때문에 출력되는 값은 개인마다, 실행할 때 마다 다를 수 있습니다.

In [2]:
A = np.matrix(np.random.random((2, 2)))  # 임의의 2x2 행렬
print(A)

[[0.47367418 0.28394749]
 [0.82580985 0.54419478]]


In [3]:
b = np.random.random((2, 2))             # 2x2의 numpy array 생성
B = np.asmatrix(b)                       # 2차원 배열을 행렬로 변환
print(B)

[[0.65490331 0.91092787]
 [0.51319412 0.37594939]]


In [4]:
C = np.mat(np.random.random((10, 5)))    # 임의의 10x5 행렬
print(C)

[[0.47190142 0.89059455 0.49284838 0.67482181 0.70300625]
 [0.65634119 0.89770408 0.5955904  0.69966841 0.86607935]
 [0.04081724 0.43216915 0.59711572 0.06691517 0.55638371]
 [0.10585509 0.1739403  0.31836127 0.77919629 0.66802378]
 [0.21974816 0.89563636 0.32125754 0.31178886 0.099196  ]
 [0.38466188 0.57284234 0.25676669 0.89516982 0.88122879]
 [0.25569756 0.79883217 0.01397952 0.10579983 0.875301  ]
 [0.45784034 0.69207561 0.58252311 0.24319391 0.87334761]
 [0.07367186 0.98328222 0.48558668 0.39257565 0.7644861 ]
 [0.82710028 0.10532776 0.64815801 0.05756485 0.03470284]]


In [5]:
D = np.mat([[3, 4], [5, 6]])             # 2차원 자료를 나타낸 리스트를 행렬로 표현
print(D)

[[3 4]
 [5 6]]


### 행렬의 다양한 연산

In [6]:
print(A.I)                               # A의 역행렬

[[ 23.3716643  -12.19476105]
 [-35.46625478  20.34299899]]


In [7]:
print(A.T)                               # A의 전치행렬

[[0.47367418 0.82580985]
 [0.28394749 0.54419478]]


In [8]:
print(linalg.det(A))                     # A의 행렬식

0.023284382855135104


In [9]:
print(np.add(A, D))                      # A와 D의 합

[[3.47367418 4.28394749]
 [5.82580985 6.54419478]]


In [10]:
print(np.subtract(A, D))                  # A와 D의 차

[[-2.52632582 -3.71605251]
 [-4.17419015 -5.45580522]]


In [11]:
print(np.divide(A, D))                    # A 나누기 D

[[0.15789139 0.07098687]
 [0.16516197 0.09069913]]


In [12]:
print(D@B)                                # D 와 B의 행렬곱
print("\n")                               # 줄 바꿈
print(np.dot(D, B))                       # 행렬곱을 numpy dot 함수로도 계산할 수 있다. 결과는 같음.

[[4.01748641 4.23658115]
 [6.35368127 6.81033566]]


[[4.01748641 4.23658115]
 [6.35368127 6.81033566]]


In [13]:
print(np.mat(np.multiply(D, B)))           # 형렬 D와 B에 대해서, 행렬곱이 아닌 대응되는 원소끼리의 단순 곱셈 수행

[[1.96470992 3.64371148]
 [2.56597061 2.25569631]]


In [14]:
print(np.mat(np.identity(2)))              # 2x2 항등행렬

[[1. 0.]
 [0. 1.]]


### 고윳값, 고유벡터 구하기

In [15]:
linalg.eigvals(A)                          # 행렬 A의 고윳값 확인

array([0.02341422+0.j, 0.99445474+0.j])

In [16]:
la, v = linalg.eig(A)                      # 고윳값을 la, 고유벡터를 v 변수로 저장.

In [17]:
l1, l2 = la                                # 고윳값을 l1, l2로 받기

In [18]:
print(v[:, 0])                             # 첫 번째 고유 벡터
print(v[:, 1])                             # 두 번째 고유 벡터

[-0.53341915  0.84585106]
[-0.47870317 -0.87797681]


### 희소행렬을 만들고 확인하기

In [19]:
C[C > 0.5] = 0                             # 행렬 C 에서 원소가 0.5 이상인 경우 해당 값을 0으로 대체.
print(C)

[[0.47190142 0.         0.49284838 0.         0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.04081724 0.43216915 0.         0.06691517 0.        ]
 [0.10585509 0.1739403  0.31836127 0.         0.        ]
 [0.21974816 0.         0.32125754 0.31178886 0.099196  ]
 [0.38466188 0.         0.25676669 0.         0.        ]
 [0.25569756 0.         0.01397952 0.10579983 0.        ]
 [0.45784034 0.         0.         0.24319391 0.        ]
 [0.07367186 0.         0.48558668 0.39257565 0.        ]
 [0.         0.10532776 0.         0.05756485 0.03470284]]


In [20]:
H = sparse.csr_matrix(C)                    # C를 희소행렬 형태로 변환
H.todense()                                 # H를 일반적인 행렬(dense matrix) 형태로 변환

matrix([[0.47190142, 0.        , 0.49284838, 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ],
        [0.04081724, 0.43216915, 0.        , 0.06691517, 0.        ],
        [0.10585509, 0.1739403 , 0.31836127, 0.        , 0.        ],
        [0.21974816, 0.        , 0.32125754, 0.31178886, 0.099196  ],
        [0.38466188, 0.        , 0.25676669, 0.        , 0.        ],
        [0.25569756, 0.        , 0.01397952, 0.10579983, 0.        ],
        [0.45784034, 0.        , 0.        , 0.24319391, 0.        ],
        [0.07367186, 0.        , 0.48558668, 0.39257565, 0.        ],
        [0.        , 0.10532776, 0.        , 0.05756485, 0.03470284]])

In [21]:
sparse.isspmatrix_csr(H)                    # 희소행렬 여부 확인

True