# PCA(Principal Component Analysis)

### 기본 라이브러리 불러오기

In [1]:
import numpy as np
from sklearn.decomposition import PCA #PCA를 위한 함수

### 3개의 열을 가진 임의의 데이터셋 생성

In [2]:
M = np.array([[-1, -1, -1], [-2, -1, 2], 
              [-3, -2, 0], [1, 1, 2], 
              [2, 1, 1], [3, 2, 4], 
              [2, 0, 3], [3, 5, 1], 
              [4, 2, 3], [3, 3, 2]])

### 주성분 분석
- 주성분 개수를 2개로 하여 임의의 데이터 셋 M을 2개의 주성분으로 축소해 보자. 

In [3]:
pca = PCA(n_components=2)
pca.fit(M)
PC = pca.transform(M)

### 고윳값, 고유 벡터 나타내기
- w를 고윳값, V를 고유 벡터라고 저장한다.
- 고윳값(Eigenvalue)
- 고유벡터(Eigenvector)

In [4]:
w, V = np.linalg.eig(pca.get_covariance())
print("고윳값 : ",w)
print("고유벡터 : ",V)

고윳값 :  [10.08253384  0.51151013  1.81706715]
고유벡터 :  [[ 0.73743194  0.66568678  0.11425952]
 [ 0.60957069 -0.58308589 -0.53706091]
 [ 0.29089124 -0.46569513  0.83576931]]


### 원 데이터를 나타내는 주성분 세 개
- T : 전치 행렬
- dot : 행렬곱

In [5]:
V.T.dot(M.T).T

array([[-1.63789386,  0.38309423, -0.41296792],
       [-1.50265209, -1.67967793,  1.98008049],
       [-3.43143719, -0.83088857,  0.73134327],
       [ 1.9287851 , -0.84878936,  1.24873722],
       [ 2.3753258 ,  0.28259255,  0.52722744],
       [ 4.59500215, -1.03189193,  2.61173397],
       [ 2.3475376 , -0.06571181,  2.73582697],
       [ 5.55104049, -1.38406422, -1.5067567 ],
       [ 5.04154285,  0.09948998,  1.89022418],
       [ 4.62279035, -0.68358757,  0.40313444]])